// data 是一個陣列裡面每一筆題目資料是一個物件 Object 用一對大括號表示
// 每一筆題目資料物件都會有 title, descript, a, b, c, d, answer 這七個屬性

const data = [{
        title: "條件判斷",
        description: "\n小明用網頁搭配 JS 寫了一隻程式來做簡單的加法計算，這隻程式如下，\n請問執行此程式，並輸入 30, 80 請問跳出什麼訊息？\n\nlet a = prompt('加數：');\nlet b = prompt('被加數：');\n\nlet c = a + b;\nalert('總和：' + c);\n",
        a: "30",
        b: "80",
        c: "3080",
        d: "程式會出錯無法執行",
        answer: "c",
    },
    {
        title: "條件判斷",
        description: "\n執行以下程式，並輸入 123456789 請問會印出什麼？\n\nlet password = prompt('請輸入金庫密碼')\n\nif (password == 123456789) {\n    console.log('密碼正確')\n} else {\n    console.log('密碼錯誤')\n}\n",
        a: "密碼正確",
        b: "密碼錯誤",
        c: "什麼都不會印",
        d: "程式會出錯無法執行",
        answer: "a",
    },
    {
        title: "條件判斷",
        description: "\n請問執行以下程式輸入 30, 30 會印出什麼？\n\nlet a = Number(prompt('輸入：')) \nlet b = Number(prompt('輸入：'))\n\nif (a > b) {\n    console.log('a 比較大')\n} else {\n    console.log('b 比較大')\n}\n",
        a: "a 比較大",
        b: "b 比較大",
        c: "一樣大",
        d: "什麼都不會印",
        answer: "b",
    },
    {
        title: "條件判斷",
        description: "\n請問在輸入合法的三角形三個邊長情況下，何種三角形程式判斷會有錯誤的結果？\n\nlet a = Number(prompt('三角形第一個邊長：'))\nlet b = Number(prompt('三角形第二個邊長：'))\nlet c = Number(prompt('三角形第三個邊長：'))\n\nif (a == b || b == c || c == a) {\n    console.log('等腰三角形')\n}\nelse if (a == b && b == c) {\n    console.log('正三角形')\n}\nelse {\n    console.log('三邊不等長三角形')\n}\n",
        a: "正三角形",
        b: "等腰三角形",
        c: "三邊不等長三角形",
        d: "無錯誤",
        answer: "a",
    },
    {
        title: "條件判斷",
        description: "\n執行以下程式分別輸入 10, 10, 5 請問程式會印出什麼？\n\nlet a = Number(prompt('a'))\nlet b = Number(prompt('b'))\nlet c = Number(prompt('c'))\n\nif (a > b) {\n    if (a > c) {\n        console.log('a 最大')\n    }\n    else {\n        console.log('b 最大')\n    }\n} else {\n    if (b > c) {\n        console.log('b 最大')\n    }\n    else {\n        console.log('c 最大')\n    }\n}\n",
        a: "a 最大",
        b: "b 最大",
        c: "c 最大",
        d: "什麼都不會印出來",
        answer: "b",
    },
    {
        title: "迴圈",
        description: "\n執行以下程式後以下敘述何者錯誤？\n\ni = 0\nwhile (i < 100) {\n    console.log(i)\n    i = i + 5\n}\n",
        a: "此迴圈會執行 100 次",
        b: "印出最小的數值是 0",
        c: "印出最大的數值是 95",
        d: "數值會從小印到大",
        answer: "a",
    },
    {
        title: "陣列",
        description: "\n請問執行以下程式最後會印出什麼？\n\nlet arr = ['A', 'B', 'C'];\narr.push('D');\narr.push('E');\narr.pop();\nconsole.log(arr);",
        a: "['A', 'B', 'C', 'D', 'E']",
        b: "['A', 'B', 'C', 'D']",
        c: "['A', 'B', 'C']",
        d: "['A', 'B']",
        answer: "b",
    },
    {
        title: "函式",
        description: "請問以下程式會印出什麼？\n\nfunction add(a, b) {\n    return a + b\n}\n\nconsole.log(add(add(10, 20), add(30, 40)))\n",
        a: "100",
        b: "110",
        c: "120",
        d: "130",
        answer: "a",
    },
    {
        title: "迴圈與四則運算",
        description: "執行以下程式最後會印出什麼？\n\narr = ['1', '2', '3', '4', '5']\n\nlet s = '';\nfor (let i = 0; i < arr.length; i++) {\n    s = s + arr[i];\n}\n\nconsole.log(s)\n",
        a: "15",
        b: "12345",
        c: "54321",
        d: "程式會出錯",
        answer: "b",
    },
    {
        title: "二維陣列",
        description: "\n請問執行以下程式分別會印出什麼？\n\nlet grid = [\n  ['A', 'B', 'C'],\n  ['D', 'E', 'F'],\n  ['G', 'H', 'I'],\n]\n\nconsole.log(grid[2][2])\n",
        a: "A",
        b: "E",
        c: "I",
        d: "H",
        answer: "c",
    },
]